<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sektoral_disnaker_model extends CI_Model
{

    public $table = 'sektoral_disnaker';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,NIK,nm_lengkap,gelar_belakang,tempat_lahir,tgl_lahir,jenis_kelamin,agama,status_perkawinan,alamat,nama_wilayah,nm_instansi');
        $this->datatables->from('sektoral_disnaker');
        //add this line for join
        //$this->datatables->join('table2', 'sektoral_disnaker.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('sektoral_disnaker/read/$1'),'Read')." | ".anchor(site_url('sektoral_disnaker/update/$1'),'Update')." | ".anchor(site_url('sektoral_disnaker/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('NIK', $q);
	$this->db->or_like('nm_lengkap', $q);
	$this->db->or_like('gelar_belakang', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('status_perkawinan', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('nama_wilayah', $q);
	$this->db->or_like('nm_instansi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('NIK', $q);
	$this->db->or_like('nm_lengkap', $q);
	$this->db->or_like('gelar_belakang', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('status_perkawinan', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('nama_wilayah', $q);
	$this->db->or_like('nm_instansi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Sektoral_disnaker_model.php */
/* Location: ./application/models/Sektoral_disnaker_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-21 06:45:51 */
/* http://harviacode.com */